<?php

namespace ContainerMV9yoxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RsX3FKrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.rsX3FKr' shared service.
     *
     * @return \App\Controller\JWTTokenManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::login()": the $JWTManager argument is type-hinted with the non-existent class or interface: "App\\Controller\\JWTTokenManagerInterface". Did you forget to add a use statement?');
    }
}
