<?php

namespace ContainerMV9yoxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllersignupService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QkiXjTi.App\Controller\UserController::signup()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QkiXjTi.App\\Controller\\UserController::signup()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['privates', '.errored..service_locator.QkiXjTi.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.QkiXjTi": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManager' => 'Doctrine\\ORM\\EntityManager',
            'serializer' => '?',
            'validator' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\UserController::signup()', $container);
    }
}
