<?php

namespace ContainerCYEy3Uz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W00ICEXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W00ICEX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W00ICEX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator._1ARgjp.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\UserController::signup' => ['privates', '.service_locator.QkiXjTi.App\\Controller\\UserController::signup()', 'getUserControllersignupService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.HS5J6h6.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator._1ARgjp.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\UserController:signup' => ['privates', '.service_locator.QkiXjTi.App\\Controller\\UserController::signup()', 'getUserControllersignupService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.HS5J6h6.App\\Controller\\UserController::login()', 'getUserControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\UserController::signup' => '?',
            'App\\Controller\\UserController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\UserController:signup' => '?',
            'App\\Controller\\UserController:login' => '?',
        ]);
    }
}
