<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCYEy3Uz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCYEy3Uz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCYEy3Uz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCYEy3Uz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCYEy3Uz\App_KernelDevDebugContainer([
    'container.build_hash' => 'CYEy3Uz',
    'container.build_id' => '224e46d3',
    'container.build_time' => 1729153598,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCYEy3Uz');
