<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFr6tk7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFr6tk7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFr6tk7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFr6tk7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFr6tk7\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFr6tk7',
    'container.build_id' => 'cfcd5e3f',
    'container.build_time' => 1728996569,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFr6tk7');
